### ISSUE TITLE
confusion about  nr database

### ISSUE THREAD

**Issue by shiyi-pan** [enormandeau/go_enrichment#5]
Hi, I want download the nr database and find the nr.00.tar.gz (16G) is much bigger other nr.**.tar.gz (1G-2G) files . is there some redundancy between nr.00.tar.gz and others ? should I download all of them or just download nr.00.tar.gz ?

**Comment by enormandeau** [comment]
Hi. I don't know the answer to your questions unfortunately but I think I remember that the 00 file is needed too.
